// Shared parts of every generated document (docs/CONTENT.md §11): the SDL header block, the
// tracking ID line, the tamper-evident pouch line and the legal footer. Used by the admin
// Document Center papers (which become the PDFs) and by ShipmentDocuments.
import React from 'react';
import { DOMAIN, LEGAL_NAME, LOGO, LOGO_ALT } from '../config/brand';
import { useCompanyContact } from '../utils/useCompanyContact';
import type { DocumentType } from '../types/admin';
import type { TransportMode } from '../shared/transportMode';
import './DocumentBrand.css';

/** §11 title for a document type. A transport document is an air waybill when the main leg flies. */
export function documentTitle(docType: DocumentType, mode?: TransportMode): string {
  switch (docType) {
    case 'BOL':
      return mode === 'Air' ? 'Air Waybill / House Waybill' : 'Bill of Lading';
    case 'INVOICE':
      return 'Commercial Invoice';
    case 'SHIPPING_LABEL':
      return 'Shipping Label';
    case 'RECEIPT':
      return 'Shipment Receipt';
    case 'INSURANCE':
      return 'Certificate of Cargo Insurance';
    default:
      return 'Shipment Document';
  }
}

/** Logo, legal name and "{address} · {email} · {domain}" (the address is left out when empty). */
export const DocumentHeaderBrand: React.FC<{ className?: string }> = ({ className = '' }) => {
  const { address, email } = useCompanyContact();
  return (
    <div className={`sdl-doc-brand ${className}`}>
      <img src={LOGO} alt={LOGO_ALT} className="doc-preview-logo-img" />
      <strong className="sdl-doc-legal-name">{LEGAL_NAME}</strong>
      <span className="sdl-doc-contact-line">{[address, email, DOMAIN].filter(Boolean).join(' · ')}</span>
    </div>
  );
};

export const DocumentIdLine: React.FC<{ trackingId: string }> = ({ trackingId }) => (
  <div className="sdl-doc-id-line">
    Tracking ID / Waybill No.: <strong className="font-mono">{trackingId}</strong>
  </div>
);

export const DocumentPouchLine: React.FC<{ sealNumber: string }> = ({ sealNumber }) => (
  <div className="sdl-doc-pouch-line">
    SDL Tamper-Evident Document Pouch · Seal No. <strong className="font-mono">{sealNumber}</strong>
  </div>
);

export const DocumentLegalFooter: React.FC = () => (
  <p className="sdl-doc-legal-footer">
    This document was generated by {LEGAL_NAME}. Carriage is subject to SDL's Shipping Terms at {DOMAIN}/#/legal.
  </p>
);
